name: ci

on:
  push:
    branches:
      - '**'

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16.6.1

      - run: npm install

      - run: npm run test

  auto-generation:
    if: github.repository == 'sirjonasxx/G-ExtensionStore'
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16.6.1

      - run: npm install

      - run: npm run auto-generate

      - run: npm run discord:publish
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}

#      - run: npm run twitter:publish
#        env:
#          TWITTER_APPKEY: ${{ secrets.TWITTER_APPKEY }}
#          TWITTER_APPSECRET: ${{ secrets.TWITTER_APPSECRET }}
#          TWITTER_ACCESSTOKEN: ${{ secrets.TWITTER_ACCESSTOKEN }}
#          TWITTER_ACCESSSECRET: ${{ secrets.TWITTER_ACCESSSECRET }}

      - run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add ./.auto-generated/*
          git commit -m "Update .auto-generated/ folder" || true

      - name: Push changes  # push the output folder to your repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
